### ISSUE TITLE
TDD

### ISSUE THREAD

**Issue by Dauliac** [conformism/raisin#1]
@thomaslepoix 

For some convenient reasons, I'll do TDD.

Do you know any cool kid and modern c++ test framework.

I saw that:https://github.com/catchorg/Catch2
 - [x] DO you know it ?
 - [x] Is it a cool kid tool

**Comment by thomaslepoix** [comment]
IMHO Catch2 currently is the best framework around.

Take a look to this other project of mine for an usage / cmake integration example : https://github.com/Open-RFlab/openemsh
